@Copilot_HostAddress = http://localhost:5188

GET {{Copilot_HostAddress}}/product
Accept: application/json

###

POST {{Copilot_HostAddress}}/product
Content-Type: application/json

{
  "sku": "string",
  "name": "string",
  "description": "string"
}